app:
  watch-path: ${APP_WATCH_PATH:./watch}
  qr-code-output-path: ${APP_QRCODE_PATH:./qrcodes}
  max-depth: 30
  health-check-interval: 60000

logging:
  level:
    org.zcl.filewatcher: INFO
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
      force-request: true
      force-response: true